# tests are written using pytest
language: python
python:
  - 3.6
dist: trusty
sudo: required
services:
- docker
install: 'pip install docker'
script:
  - id
  - getent passwd
  - chmod 0777 /tmp
  - hack/ci.sh
